# Generated by Django 4.1.7 on 2023-07-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenrePick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
